# Generated by Django 5.1.4 on 2025-02-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
