# Generated by Django 5.1.4 on 2025-02-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
