# Generated by Django 5.1.4 on 2025-02-19 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('E', 'Engineer')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, help_text='Phone number must be exactly 11 or 12 characters long.', unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(12)]),
            preserve_default=False,
        ),
    ]
