# Generated by Django 5.1.4 on 2025-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
