# Generated by Django 5.1.3 on 2024-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('description', models.TextField(default='', max_length=3000)),
                ('Care_Guide', models.TextField(blank=True, default='', max_length=3000)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/%y/%m/%d')),
                ('category', models.CharField(choices=[('Plants', 'Plants'), ('Seeds', 'Seeds'), ('Pots', 'Pots')], max_length=40)),
            ],
        ),
    ]
