# Generated by Django 5.1.4 on 2025-02-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='post_name',
        ),
    ]
